[package]
name = "sentinel"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
clap = { version = "4.5.28", features = ["derive"] }
futures = "0.3.31"
notify = "8.0.0"
tokio = { version = "1", features = ["full"] }
